name: Label auto-merge PRs

on:
  push:
    branches-ignore:
      - main
      - indev
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "work-branch"
          base: main
          title: "Automatic pull request"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
