name: Merge branch with labeled
on:
  pull_request:
    types: [ labeled ]
jobs:
  merge-branch:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master

      - name: Merge by labeled
        uses: devmasx/merge-branch@master
        with:
          label_name: 'merged indev'
          target_branch: 'indev'
          github_token: ${{ github.token }}
